services:
  postgres:
    image: 'postgres:12'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3.7-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=rabbitmq'
      - 'RABBITMQ_DEFAULT_USER=rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'